### ISSUE TITLE
Running Routinator behind reverse proxy with Docker

### ISSUE THREAD

**Issue by bswinnerton** [NLnetLabs/routinator#329]
Hello,

I'm having a very difficult time getting routinator working. 

I'm trying to use a reverse proxy, as recommend in the [documentation](https://rpki.readthedocs.io/en/latest/routinator/daemon.html#the-http-service):

> Please note that this server is intended to run on your internal network and doesn’t offer HTTPS natively. If this is a requirement, you can for example run Routinator behind an NGINX reverse proxy.

But I think that the way that Routinator binds to ports might be confusing the reverse proxy ([Traefik](https://containo.us/traefik/) in this case). The reverse proxy logs are filled with:

```
traefik    | time="2020-05-12T02:34:57Z" level=error msg="service \"routinator-routinator\" error: unable to find the IP address for the container \"/routinator\": the server is ignored" container=routinator-routinator-501f908608811495a27bf2cc19982ef29f79388aa6273506d59d749006d4f34f providerName=docker
```

And 500s are returned from the reverse proxy. No requests seem to make it to Routinator.

I have tried overriding the `CMD`

https://github.com/NLnetLabs/routinator/blob/be1e1c5949c90bd9dbcf450b006e9808ae707962/Dockerfile#L52

with:

```
-v server --http 127.0.0.1:8323 --rtr 127.0.0.1:3323
```

```
-v server --http 0.0.0.0:8323 --rtr 0.0.0.0:3323
```

As well as the docker container's ip address, all to no avail. I also was very confused by the documentation's references to HTTP running on `8323`, but in Docker using `9556`.

I suspect that this is not necessarily a problem with Routinator itself, or Traefik either, but how they interact with one another. I'm mostly curious if there is anything non-standard with how Routinator binds to addresses.

The Docker configuration is as follows:

```yaml
version: '3'

services:
  routinator:
    image: nlnetlabs/routinator
    container_name: routinator
    restart: unless-stopped
    command: '-v server --http 0.0.0.0:8323 --rtr 0.0.0.0:3323'
    expose:
      - 8323
    ports:
      - '3323:3323'
    networks:
      - 'traefik'
    volumes:
      - tals:/home/routinator/.rpki-cache/tals
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.routers.routinator.rule=Host(`rpki.tld`)'
      - 'traefik.http.routers.routinator.entrypoints=websecure'
      - 'traefik.http.routers.routinator.tls.certresolver=letsencrypt'

volumes:
  tals:

networks:
  traefik:
    external: true
```
