### ISSUE TITLE
Feature: RRDP serial as a metric

### ISSUE THREAD

**Issue by ties** [NLnetLabs/routinator#477]
As a repository operator, to be sure that my repository is getting updates, I like to monitor that the RRDP serial is increasing.  For this I would like to have the RRDP serial as a Prometheus metric.

```yaml
name: SerialReset
expr: rrdp_serial{address=~".*[host]/.*"} < max_over_time(rrdp_serial{address=~".*[host]/.*"}[30m])
labels:
severity: P4
annotations:
description: {{ $labels.group }} RRDP serial at {{ $labels.address }} reset from {{ with printf "max_over_time(rrdp_serial{address='%s'}[30m])" .Labels.address | query }}{{ . | first | value }}{{end}} to {{ $value }} (in the last 30m) according to {{ $labels.instance }}.
summary: {{ $labels.group }} RRDP serial at {{ $labels.address }} reset to {{ $value }}.
```

For bonus points, track accepted/rejected rrdp updates as well, such as OctoRPKI does:
```yaml
name: OctoRPKIRRDPErrors
expr: rrdp_errors{address="https://[host]/rrdp/notification.xml"} > 0
labels:
severity: P1
annotations:
description: OctoRPKI found {{ humanize $value }} RRDP errors for {{ $labels.address} from {{ $labels.instance }}.
summary: OctoRPKI found {{ humanize $value }} RRDP errors for {{ $labels.address}} on {{ $labels.hostname }}
```

```yaml
name: OctoRPKIRRDPDeltaIncreasing
expr: (increase(rrdp_serial{address=~".*[host]/.*"}[1h30m]) == 0)
labels:
severity: P1
annotations:
description: OctoRPKI did see {{ $value }} new RRDP serials at {{ $labels.address }} during the last 90  minutes from {{ $labels.instance }}.
summary: No new RRDP serial at {{ $labels.address }} for 90m.
```
